leftnav:
- identifier: b2588aa9-689f-4c7b-839d-bdb6692eb93f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 52e203d2-2d0d-9bb1-0143-e079117c1785
  name: Lectures and Readings
  pageRef: /pages/other
  weight: 20
- identifier: a9fdaa54-9757-e4cc-9482-bf3b46f720fe
  name: Exams
  pageRef: /pages/exams
  weight: 30
- identifier: 8c2290e3-7cf3-c24a-05ef-53a134749585
  name: Projects
  pageRef: /pages/projects/
  weight: 40
